In [113]:
import pandas as pd
import Scrape_pokemon_functions as sp
import importlib

In [114]:
import Scrape_pokemon_functions as sp
importlib.reload(sp)
import Scrape_pokemon_functions as sp

In [128]:
dropdown = pd.read_csv('Data_Files/dropdown_df.csv')

In [206]:
pokemon = "Meowscarada"

In [207]:
df = dropdown[dropdown['Decklists'].str.contains(pokemon)]
x = df['Expansion'].unique()
y = [df[(df['Expansion'] == expansion) & (df['Player_Total'] > 300)]['Placement'].sort_values()[:10].mean() for expansion in df['Expansion'].unique()]

In [176]:
df['Expansion'].unique()

array(['Genetic Apex', 'Mythical Island', 'Space-Time Smackdown',
       'Triumphant Light', 'Shining Revelry', 'Celestial Guardians',
       'Extradimensional Crisis', 'Eevee Grove', 'Wisdom of Sea and Sky',
       'Secluded Springs'], dtype=object)

In [177]:
row = df[(df['Expansion'] == 'Eevee Grove')].iloc[0]# & (df['Player_Total'] > 300)].sort_values(['Placement','Player_Total'], ascending=[True,False]).loc[0]

print(row)

# comment

Deck                                         Incineroar ex Greninja
Player                                                Arthur1248421
Date                                                     2025-06-25
Tournament                      🏆 #2 ITP Weekly Tournament 🏆 || 40€
Placement                                                     124.0
Player_Total                                                  154.0
Score                                                     0 - 1 - 0
Decklist_url      /tournament/68597559c4596e812236173d/player/ar...
Tournament_url         /tournament/68597559c4596e812236173d/details
Decklists         {"Amount":{"0":"2","1":"1","2":"2","3":"1","4"...
Expansion                                               Eevee Grove
Name: 28356, dtype: object

In [54]:
row

Deck                                         Aerodactyl ex Primeape
Player                                                          Duo
Date                                                     2025-01-11
Tournament             Ursiiday's Pocket Weekly #11 • 400 USD Prize
Placement                                                       7.0
Player_Total                                                 1782.0
Score                                                    10 - 2 - 1
Decklist_url      /tournament/6779bb0bed2c78098c6b086b/player/du...
Tournament_url         /tournament/6779bb0bed2c78098c6b086b/details
Decklists         {"Amount":{"0":"2","1":"2","2":"2","3":"2","4"...
Expansion                                           Mythical Island
Name: 4816, dtype: object

In [178]:
df[df['Player_Total'] > 100].sort_values(['Placement','Player_Total'], ascending=[True, False]).iloc[0]

Deck                                           Gyarados ex Greninja
Player                                                         Lead
Date                                                     2025-01-04
Tournament             Ursiiday's Pocket Weekly #10 • 400 USD Prize
Placement                                                       1.0
Player_Total                                                 1995.0
Score                                                    14 - 1 - 0
Decklist_url      /tournament/67708cb5ed2c78098c69d24f/player/le...
Tournament_url         /tournament/67708cb5ed2c78098c69d24f/details
Decklists         {"Amount":{"0":"2","1":"2","2":"2","3":"2","4"...
Expansion                                           Mythical Island
Name: 4636, dtype: object

In [208]:
num_df = df[(df['Player_Total'] > 200) & (df['Placement'] <= 64)]

In [209]:
len(num_df)

79

In [210]:
ff = pd.DataFrame(data=[len(num_df),len(num_df[num_df['Placement'] <= 16]),
                                   len(num_df[num_df['Placement'] <= 8]),
                                       len(num_df[num_df['Placement'] <= 4]),
                                           len(num_df[num_df['Placement'] <= 2]),
                                               len(num_df[num_df['Placement'] <= 1])],
             index=['Top 64 Finishes',
                    'Top 16 Finishes',
                    'Top 8 Finishes',
                    'Top 4 Finishes',
                    '2nd Place Finishes',
                    'Tournament Wins'])

In [211]:
ff

                     0
Top 64 Finishes     79
Top 16 Finishes     31
Top 8 Finishes      18
Top 4 Finishes       8
2nd Place Finishes   4
Tournament Wins      1

In [186]:
df = dropdown[dropdown['Decklists'].str.contains('Aerodactyl ex')]
df_to_use = df[(df['Player_Total'] > 300) & (df['Placement'] <= 64)]
final_df = sp.create_finishes_df(df_to_use)

In [138]:
type(final_df[0])

pandas.core.series.Series

In [160]:
x = pd.DataFrame({'Finishes':['Top 64 Finishes',
                    'Top 16 Finishes',
                    'Top 8 Finishes',
                    'Top 4 Finishes',
                    '2nd Place Finishes',
                    'Tournament Wins'],
              'Count':[len(num_df),len(num_df[num_df['Placement'] <= 16]),
                                   len(num_df[num_df['Placement'] <= 8]),
                                       len(num_df[num_df['Placement'] <= 4]),
                                           len(num_df[num_df['Placement'] <= 2]),
                                               len(num_df[num_df['Placement'] <= 1])]})

In [168]:
def print_df(df):
   # This code delete index and columns names
   df_ = df.copy()
   df_.columns = ['', '']
   df_.index = ['' for _ in range(len(df))]
   return df_

print_df(x)

     Top 64 Finishes  3
     Top 16 Finishes  0
      Top 8 Finishes  0
      Top 4 Finishes  0
  2nd Place Finishes  0
     Tournament Wins  0