### Most Dominant EX Pokemon

In [10]:
import pandas as pd
import Scrape_pokemon_functions as sp
import importlib

In [11]:
import Scrape_pokemon_functions as sp
importlib.reload(sp)
import Scrape_pokemon_functions as sp

In [12]:
df = pd.read_csv('Data_Files/dropdown_df.csv')

In [2]:
with open('Data_Files/best_names.txt', 'r') as f:
    names = f.readlines()
names = [name.strip() for name in names]

In [134]:
expansions = []
for name in names:
    exp = df[df['Decklists'].str.contains(name)].sort_values('Date').iloc[0]['Expansion']
    expansions.append(exp)

In [27]:
def filter_top_finishes(df, pokemon):
    df1 = df[df['Decklists'].str.contains(pokemon)]
    df2 = df1[(df1['Player_Total'] >= 200) & (df1['Placement'] <= 64)].sort_values(['Placement','Player_Total'], ascending=[True, False])
    return df2

# comment

In [17]:
#filter_top_finishes(df, names[7])

In [ ]:
def create_finishes_df(df):
    new = pd.DataFrame({'Finishes':['Top 64 Finishes',
                    'Top 16 Finishes',
                    'Top 8 Finishes',
                    'Top 4 Finishes',
                    '2nd Place Finishes',
                    'Tournament Wins'],
                        'Count':[len(df),len(df[df['Placement'] <= 16]),
                                   len(df[df['Placement'] <= 8]),
                                       len(df[df['Placement'] <= 4]),
                                           len(df[df['Placement'] <= 2]),
                                               len(df[df['Placement'] <= 1])]})

In [40]:
sp.create_finishes_df(filter_top_finishes(df, names[0]))

             Finishes  Count
0     Top 64 Finishes    150
1     Top 16 Finishes     59
2      Top 8 Finishes     36
3      Top 4 Finishes     17
4  2nd Place Finishes      7
5     Tournament Wins      1

In [115]:
def make_score(df):
    df1 = sp.create_finishes_df(df)
    score = df1['Count'][1] * 3
    score += df1['Count'][2] * 6
    score += df1['Count'][3] * 10
    score += df1['Count'][4] * 15
    score += df1['Count'][5] * 25
    score += df1['Count'][0]
    return score

In [116]:
make_score(filter_top_finishes(df, names[0]))

np.int64(843)

In [151]:
maxs = max(scores['Score'])
mins = min(scores['Score'])

In [145]:
for i in range(len(scores)):
    if scores['Expansion'][i] == 'Genetic Apex':
        scores['Score'][i] = float(scores['Score'][i] * .5)
    elif scores['Expansion'][i] == 'Mythical Island':
        scores['Score'][i] = float(scores['Score'][i] * .6)
    elif scores['Expansion'][i] == 'Space-Time Smackdown':
        scores['Score'][i] = float(scores['Score'][i] * .7)
    elif scores['Expansion'][i] == 'Triumphant Light':
        scores['Score'][i] = float(scores['Score'][i] * .8)
    elif scores['Expansion'][i] == 'Shining Revelry':
        scores['Score'][i] = float(scores['Score'][i] * .9)
    elif scores['Expansion'][i] == 'Celestial Guardians':
        scores['Score'][i] = float(scores['Score'][i] * 1)
    elif scores['Expansion'][i] == 'Extradimensional Crisis':
        scores['Score'][i] = float(scores['Score'][i] * 1.1)
    elif scores['Expansion'][i] == 'Eevee Grove':
        scores['Score'][i] = float(scores['Score'][i] * 1.2)
    elif scores['Expansion'][i] == 'Wisdom of Sea and Sky':
        scores['Score'][i] = float(scores['Score'][i] * 1.3)
    elif scores['Expansion'][i] == 'Secluded Springs':
        scores['Score'][i] = float(scores['Score'][i] * 1.4)

/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/2644388384.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scores['Score'][i] = float(scores['Score'][i] * .6)
/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/2644388384.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '505.79999999999995' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  scores['Score'][i] = float(scores['Score'][i] * .6)

In [150]:
for i in range(len(scores)):
    if scores['Expansion'][i] == 'Genetic Apex':
        scores['Score'][i] = float(scores['Score'][i] * .1)
    elif scores['Expansion'][i] == 'Mythical Island':
        scores['Score'][i] = float(scores['Score'][i] * .2)
    elif scores['Expansion'][i] == 'Space-Time Smackdown':
        scores['Score'][i] = float(scores['Score'][i] * .3)
    elif scores['Expansion'][i] == 'Triumphant Light':
        scores['Score'][i] = float(scores['Score'][i] * .4)
    elif scores['Expansion'][i] == 'Shining Revelry':
        scores['Score'][i] = float(scores['Score'][i] * .5)
    elif scores['Expansion'][i] == 'Celestial Guardians':
        scores['Score'][i] = float(scores['Score'][i] * .6)
    elif scores['Expansion'][i] == 'Extradimensional Crisis':
        scores['Score'][i] = float(scores['Score'][i] * .7)
    elif scores['Expansion'][i] == 'Eevee Grove':
        scores['Score'][i] = float(scores['Score'][i] * .8)
    elif scores['Expansion'][i] == 'Wisdom of Sea and Sky':
        scores['Score'][i] = float(scores['Score'][i] * .9)
    elif scores['Expansion'][i] == 'Secluded Springs':
        scores['Score'][i] = float(scores['Score'][i] * 1)

/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/1672384416.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scores['Score'][i] = float(scores['Score'][i] * .2)
/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/1672384416.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '168.60000000000002' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  scores['Score'][i] = float(scores['Score'][i] * .2)

In [152]:
normalized = []
for score in scores['Score']:
    norm = (score / ((maxs - mins))) * 100
    normalized.append(norm)
scores['Normalized_Score'] = normalized

In [153]:
pd.set_option('display.max_rows', 100)
scores.sort_values('Normalized_Score',ascending=False).reset_index(drop=True)

                Pokemon   Score                Expansion  Normalized_Score
0           Giratina ex  2477.5          Shining Revelry        100.000000
1            Sylveon ex  1821.6              Eevee Grove         73.525732
2            Darkrai ex  1704.3     Space-Time Smackdown         68.791120
3             Arceus ex  1304.0         Triumphant Light         52.633703
4           Buzzwole ex  1083.6  Extradimensional Crisis         43.737639
5                Mew ex   833.6          Mythical Island         33.646821
6            Suicune ex   796.0         Secluded Springs         32.129162
7              Eevee ex   794.4              Eevee Grove         32.064581
8             Palkia ex   685.8     Space-Time Smackdown         27.681130
9             Celebi ex   582.2          Mythical Island         23.499495
10          Guzzlord ex   497.7  Extradimensional Crisis         20.088799
11           Flareon ex   496.8              Eevee Grove         20.052472
12          Gyarados ex   493.2          Mythical Island         19.907164
13               A2b-10   439.0          Shining Revelry         17.719475
14            Dialga ex   408.9     Space-Time Smackdown         16.504541
15         Tapu Koko ex   377.3  Extradimensional Crisis         15.229062
16                A1-96   370.6             Genetic Apex         14.958628
17            Espeon ex   369.0    Wisdom of Sea and Sky         14.894046
18            Zapdos ex   351.2             Genetic Apex         14.175580
19         Exeggutor ex   314.2             Genetic Apex         12.682139
20           Moltres ex   282.0             Genetic Apex         11.382442
21           Weavile ex   249.3     Space-Time Smackdown         10.062563
22           Leafeon ex   237.6         Triumphant Light          9.590313
23           Gallade ex   219.9     Space-Time Smackdown          8.875883
24            Mewtwo ex   214.9             Genetic Apex          8.674067
25          Arcanine ex   208.5             Genetic Apex          8.415742
26                A1-36   192.8             Genetic Apex          7.782038
27          Articuno ex   189.7             Genetic Apex          7.656912
28          Solgaleo ex   180.6      Celestial Guardians          7.289606
29        Aerodactyl ex   168.6          Mythical Island          6.805247
30         Decidueye ex   154.2      Celestial Guardians          6.224016
31         Pachirisu ex   139.8     Space-Time Smackdown          5.642785
32          Garchomp ex   137.2         Triumphant Light          5.537841
33               A2b-22   133.0          Shining Revelry          5.368315
34        Incineroar ex   125.4      Celestial Guardians          5.061554
35           Yanmega ex   119.4     Space-Time Smackdown          4.819374
36           Snorlax ex   100.0              Eevee Grove          4.036327
37           Starmie ex    93.8             Genetic Apex          3.786075
38            Raikou ex    93.0         Secluded Springs          3.753784
39         Dragonite ex    77.6              Eevee Grove          3.132190
40             Ho-Oh ex    72.9    Wisdom of Sea and Sky          2.942482
41            Crobat ex    61.2    Wisdom of Sea and Sky          2.470232
42         Infernape ex    59.1     Space-Time Smackdown          2.385469
43           Donphan ex    47.7    Wisdom of Sea and Sky          1.925328
44           Pidgeot ex    41.0          Mythical Island          1.654894
45        Wigglytuff ex    36.7             Genetic Apex          1.481332
46             Lugia ex    36.0    Wisdom of Sea and Sky          1.453078
47         Blastoise ex    28.0             Genetic Apex          1.130172
48        Lickilicky ex    25.2     Space-Time Smackdown          1.017154
49           Machamp ex    24.5             Genetic Apex          0.988900
50          Beedrill ex    22.5          Shining Revelry          0.908174
51           Marowak ex    21.8             Genetic Apex          0.879919
52           Glaceon ex    16.8         Triumphant Light          0.678103
53           Umbreon ex    15.3    Wisdom of Sea and Sky          0.617558
54            Lapras ex    14.6             Genetic Apex          0.589304
55          Skarmory ex    13.5    Wisdom of Sea and Sky          0.544904
56         Mismagius ex    12.6     Space-Time Smackdown          0.508577
57         Probopass ex    11.2         Triumphant Light          0.452069
58      Crabominable ex    10.8      Celestial Guardians          0.435923
59          Venusaur ex    10.6             Genetic Apex          0.427851
60        Wishiwashi ex    10.2      Celestial Guardians          0.411705
61         Primarina ex     8.8              Eevee Grove          0.355197
62           Wugtrio ex     8.5          Shining Revelry          0.343088
63            Raichu ex     7.8      Celestial Guardians          0.314834
64     Alolan Raichu ex     7.8      Celestial Guardians          0.314834
65            Gengar ex     7.7             Genetic Apex          0.310797
66             Entei ex     6.0         Secluded Springs          0.242180
67            Lunala ex     3.6      Celestial Guardians          0.145308
68          Tinkaton ex     2.5          Shining Revelry          0.100908
69          Jumpluff ex     2.0         Secluded Springs          0.080727
70         Poliwrath ex     2.0         Secluded Springs          0.080727
71         Cresselia ex     1.2     Space-Time Smackdown          0.048436
72          Rayquaza ex     1.2      Celestial Guardians          0.048436
73  Paldean Clodsire ex     1.0          Shining Revelry          0.040363
74          Lycanroc ex     0.7  Extradimensional Crisis          0.028254
75    Ultra Necrozma ex     0.7  Extradimensional Crisis          0.028254
76    Alolan Dugtrio ex     0.0  Extradimensional Crisis          0.000000
77        Alolan Muk ex     0.0      Celestial Guardians          0.000000
78          Dhelmise ex     0.0      Celestial Guardians          0.000000
79           Blissey ex     0.0    Wisdom of Sea and Sky          0.000000
80           Bibarel ex     0.0          Shining Revelry          0.000000
81           Lucario ex     0.0          Shining Revelry          0.000000
82           Lanturn ex     0.0    Wisdom of Sea and Sky          0.000000
83           Kingdra ex     0.0    Wisdom of Sea and Sky          0.000000
84           Shuckle ex     0.0    Wisdom of Sea and Sky          0.000000
85         Passimian ex     0.0      Celestial Guardians          0.000000

In [159]:
def power_ranking_table(df, ex_list):
    scores = []
    expansions = []
    normalized = []
    for name in names:
        exp = df[df['Decklists'].str.contains(name)].sort_values('Date').iloc[0]['Expansion']
        expansions.append(exp)
    for name in ex_list:
        df_ = filter_top_finishes(df, name)
        score = make_score(df_)
        scores.append(score)
    scores = pd.DataFrame({'Pokemon':names,
                           'Score':scores,
                          'Expansion':expansions})
    maxs = max(scores['Score'])
    mins = min(scores['Score'])
    for i in range(len(scores)):
        if scores['Expansion'][i] == 'Genetic Apex':
            scores['Score'][i] = float(scores['Score'][i] * .55)
        elif scores['Expansion'][i] == 'Mythical Island':
            scores['Score'][i] = float(scores['Score'][i] * .6)
        elif scores['Expansion'][i] == 'Space-Time Smackdown':
            scores['Score'][i] = float(scores['Score'][i] * .65)
        elif scores['Expansion'][i] == 'Triumphant Light':
            scores['Score'][i] = float(scores['Score'][i] * .7)
        elif scores['Expansion'][i] == 'Shining Revelry':
            scores['Score'][i] = float(scores['Score'][i] * .75)
        elif scores['Expansion'][i] == 'Celestial Guardians':
            scores['Score'][i] = float(scores['Score'][i] * .8)
        elif scores['Expansion'][i] == 'Extradimensional Crisis':
            scores['Score'][i] = float(scores['Score'][i] * .85)
        elif scores['Expansion'][i] == 'Eevee Grove':
            scores['Score'][i] = float(scores['Score'][i] * .9)
        elif scores['Expansion'][i] == 'Wisdom of Sea and Sky':
            scores['Score'][i] = float(scores['Score'][i] * .95)
        elif scores['Expansion'][i] == 'Secluded Springs':
            scores['Score'][i] = float(scores['Score'][i] * 1)
    for score in scores['Score']:
        norm = (score / ((maxs - mins))) * 100
        normalized.append(norm)
    scores['Normalized_Score'] = normalized
    scores = scores.sort_values('Normalized_Score',ascending=False).reset_index(drop=True)
    return scores

In [160]:
power_ranking_table(df, names)

/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/2005196690.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scores['Score'][i] = float(scores['Score'][i] * .6)
/var/folders/h4/wzc57jcs49ggstmqwfj47qr40000gp/T/ipykernel_35290/2005196690.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '505.79999999999995' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  scores['Score'][i] = float(scores['Score'][i] * .6)

                Pokemon    Score                Expansion  Normalized_Score
0           Giratina ex  3716.25          Shining Revelry         65.415420
1            Darkrai ex  3692.65     Space-Time Smackdown         65.000000
2                Mew ex  2500.80          Mythical Island         44.020419
3             Arceus ex  2282.00         Triumphant Light         40.168984
4            Sylveon ex  2049.30              Eevee Grove         36.072874
5                 A1-96  2038.30             Genetic Apex         35.879247
6             Zapdos ex  1931.60             Genetic Apex         34.001056
7             Celebi ex  1746.60          Mythical Island         30.744587
8          Exeggutor ex  1728.10             Genetic Apex         30.418940
9            Moltres ex  1551.00             Genetic Apex         27.301531
10            Palkia ex  1485.90     Space-Time Smackdown         26.155606
11          Gyarados ex  1479.60          Mythical Island         26.044710
12          Buzzwole ex  1315.80  Extradimensional Crisis         23.161415
13            Mewtwo ex  1181.95             Genetic Apex         20.805316
14          Arcanine ex  1146.75             Genetic Apex         20.185707
15                A1-36  1060.40             Genetic Apex         18.665728
16          Articuno ex  1043.35             Genetic Apex         18.365605
17             Eevee ex   893.70              Eevee Grove         15.731385
18            Dialga ex   885.95     Space-Time Smackdown         15.594966
19           Suicune ex   796.00         Secluded Springs         14.011618
20               A2b-10   658.50          Shining Revelry         11.591269
21          Guzzlord ex   604.35  Extradimensional Crisis         10.638092
22           Flareon ex   558.90              Eevee Grove          9.838057
23           Weavile ex   540.15     Space-Time Smackdown          9.508009
24           Starmie ex   515.90             Genetic Apex          9.081148
25        Aerodactyl ex   505.80          Mythical Island          8.903362
26           Gallade ex   476.45     Space-Time Smackdown          8.386728
27         Tapu Koko ex   458.15  Extradimensional Crisis          8.064601
28           Leafeon ex   415.80         Triumphant Light          7.319134
29            Espeon ex   389.50    Wisdom of Sea and Sky          6.856187
30         Pachirisu ex   302.90     Space-Time Smackdown          5.331808
31           Yanmega ex   258.70     Space-Time Smackdown          4.553776
32          Solgaleo ex   240.80      Celestial Guardians          4.238690
33          Garchomp ex   240.10         Triumphant Light          4.226369
34         Decidueye ex   205.60      Celestial Guardians          3.619081
35        Wigglytuff ex   201.85             Genetic Apex          3.553072
36               A2b-22   199.50          Shining Revelry          3.511706
37        Incineroar ex   167.20      Celestial Guardians          2.943144
38         Blastoise ex   154.00             Genetic Apex          2.710790
39           Machamp ex   134.75             Genetic Apex          2.371942
40         Infernape ex   128.05     Space-Time Smackdown          2.254005
41           Pidgeot ex   123.00          Mythical Island          2.165112
42           Marowak ex   119.90             Genetic Apex          2.110544
43           Snorlax ex   112.50              Eevee Grove          1.980285
44            Raikou ex    93.00         Secluded Springs          1.637036
45         Dragonite ex    87.30              Eevee Grove          1.536701
46            Lapras ex    80.30             Genetic Apex          1.413484
47             Ho-Oh ex    76.95    Wisdom of Sea and Sky          1.354515
48            Crobat ex    64.60    Wisdom of Sea and Sky          1.137124
49          Venusaur ex    58.30             Genetic Apex          1.026228
50        Lickilicky ex    54.60     Space-Time Smackdown          0.961098
51           Donphan ex    50.35    Wisdom of Sea and Sky          0.886288
52            Gengar ex    42.35             Genetic Apex          0.745467
53             Lugia ex    38.00    Wisdom of Sea and Sky          0.668896
54          Beedrill ex    33.75          Shining Revelry          0.594086
55           Glaceon ex    29.40         Triumphant Light          0.517515
56         Mismagius ex    27.30     Space-Time Smackdown          0.480549
57         Probopass ex    19.60         Triumphant Light          0.345010
58           Umbreon ex    16.15    Wisdom of Sea and Sky          0.284281
59      Crabominable ex    14.40      Celestial Guardians          0.253477
60          Skarmory ex    14.25    Wisdom of Sea and Sky          0.250836
61        Wishiwashi ex    13.60      Celestial Guardians          0.239394
62           Wugtrio ex    12.75          Shining Revelry          0.224432
63            Raichu ex    10.40      Celestial Guardians          0.183066
64     Alolan Raichu ex    10.40      Celestial Guardians          0.183066
65         Primarina ex     9.90              Eevee Grove          0.174265
66             Entei ex     6.00         Secluded Springs          0.105615
67            Lunala ex     4.80      Celestial Guardians          0.084492
68          Tinkaton ex     3.75          Shining Revelry          0.066010
69         Cresselia ex     2.60     Space-Time Smackdown          0.045767
70         Poliwrath ex     2.00         Secluded Springs          0.035205
71          Jumpluff ex     2.00         Secluded Springs          0.035205
72          Rayquaza ex     1.60      Celestial Guardians          0.028164
73  Paldean Clodsire ex     1.50          Shining Revelry          0.026404
74          Lycanroc ex     0.85  Extradimensional Crisis          0.014962
75    Ultra Necrozma ex     0.85  Extradimensional Crisis          0.014962
76    Alolan Dugtrio ex     0.00  Extradimensional Crisis          0.000000
77        Alolan Muk ex     0.00      Celestial Guardians          0.000000
78          Dhelmise ex     0.00      Celestial Guardians          0.000000
79           Blissey ex     0.00    Wisdom of Sea and Sky          0.000000
80           Bibarel ex     0.00          Shining Revelry          0.000000
81           Lucario ex     0.00          Shining Revelry          0.000000
82           Lanturn ex     0.00    Wisdom of Sea and Sky          0.000000
83           Kingdra ex     0.00    Wisdom of Sea and Sky          0.000000
84           Shuckle ex     0.00    Wisdom of Sea and Sky          0.000000
85         Passimian ex     0.00      Celestial Guardians          0.000000